engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR1,PSR2"
      ignore_warnings: true
      encoding: utf-8
  phpmd:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: false
  shellcheck:
    enabled: false
ratings:
  paths:
    - "src/"
exclude_paths:
  - "tests/"
  - "docs/"
  - "bin/"
  - "vendor/"